// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cluster/v1/cluster.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberStatus int32

const (
	MemberStatus_MEMBER_STATUS_UNKNOWN MemberStatus = 0
	MemberStatus_MEMBER_STATUS_ALIVE   MemberStatus = 1
	MemberStatus_MEMBER_STATUS_SUSPECT MemberStatus = 2
	MemberStatus_MEMBER_STATUS_DEAD    MemberStatus = 3
)

// Enum value maps for MemberStatus.
var (
	MemberStatus_name = map[int32]string{
		0: "MEMBER_STATUS_UNKNOWN",
		1: "MEMBER_STATUS_ALIVE",
		2: "MEMBER_STATUS_SUSPECT",
		3: "MEMBER_STATUS_DEAD",
	}
	MemberStatus_value = map[string]int32{
		"MEMBER_STATUS_UNKNOWN": 0,
		"MEMBER_STATUS_ALIVE":   1,
		"MEMBER_STATUS_SUSPECT": 2,
		"MEMBER_STATUS_DEAD":    3,
	}
)

func (x MemberStatus) Enum() *MemberStatus {
	p := new(MemberStatus)
	*p = x
	return p
}

func (x MemberStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_v1_cluster_proto_enumTypes[0].Descriptor()
}

func (MemberStatus) Type() protoreflect.EnumType {
	return &file_cluster_v1_cluster_proto_enumTypes[0]
}

func (x MemberStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberStatus.Descriptor instead.
func (MemberStatus) EnumDescriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{0}
}

type VectorClockEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Counter       uint64                 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClockEntry) Reset() {
	*x = VectorClockEntry{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClockEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClockEntry) ProtoMessage() {}

func (x *VectorClockEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClockEntry.ProtoReflect.Descriptor instead.
func (*VectorClockEntry) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *VectorClockEntry) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *VectorClockEntry) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

type VectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*VectorClockEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *VectorClock) GetEntries() []*VectorClockEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Envelope struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	VectorClock       *VectorClock           `protobuf:"bytes,2,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`
	UpdatedAtUnixNano int64                  `protobuf:"varint,3,opt,name=updated_at_unix_nano,json=updatedAtUnixNano,proto3" json:"updated_at_unix_nano,omitempty"`
	Deleted           bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Value             string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *Envelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Envelope) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

func (x *Envelope) GetUpdatedAtUnixNano() int64 {
	if x != nil {
		return x.UpdatedAtUnixNano
	}
	return 0
}

func (x *Envelope) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Envelope) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type KeyEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Envelope      *Envelope              `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyEnvelope) Reset() {
	*x = KeyEnvelope{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyEnvelope) ProtoMessage() {}

func (x *KeyEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyEnvelope.ProtoReflect.Descriptor instead.
func (*KeyEnvelope) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *KeyEnvelope) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyEnvelope) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *Status) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Status) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	AdvertiseAddr string                 `protobuf:"bytes,3,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *NodeInfo) GetAdvertiseAddr() string {
	if x != nil {
		return x.AdvertiseAddr
	}
	return ""
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Envelope      *Envelope              `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Sync          bool                   `protobuf:"varint,3,opt,name=sync,proto3" json:"sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *PutRequest) GetSync() bool {
	if x != nil {
		return x.Sync
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Envelope      *Envelope              `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Sync          bool                   `protobuf:"varint,3,opt,name=sync,proto3" json:"sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *DeleteRequest) GetSync() bool {
	if x != nil {
		return x.Sync
	}
	return false
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *WriteResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Envelope      *Envelope              `protobuf:"bytes,3,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *GetResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type RangeScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	PageNum       int32                  `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeScanRequest) Reset() {
	*x = RangeScanRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeScanRequest) ProtoMessage() {}

func (x *RangeScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeScanRequest.ProtoReflect.Descriptor instead.
func (*RangeScanRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *RangeScanRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *RangeScanRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *RangeScanRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *RangeScanRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RangeScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Rows          []*KeyEnvelope         `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeScanResponse) Reset() {
	*x = RangeScanResponse{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeScanResponse) ProtoMessage() {}

func (x *RangeScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeScanResponse.ProtoReflect.Descriptor instead.
func (*RangeScanResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *RangeScanResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RangeScanResponse) GetRows() []*KeyEnvelope {
	if x != nil {
		return x.Rows
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{13}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Node          *NodeInfo              `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Ready         bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{14}
}

func (x *HealthResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HealthResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type ReplicatePutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Envelope      *Envelope              `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicatePutRequest) Reset() {
	*x = ReplicatePutRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicatePutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicatePutRequest) ProtoMessage() {}

func (x *ReplicatePutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicatePutRequest.ProtoReflect.Descriptor instead.
func (*ReplicatePutRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{15}
}

func (x *ReplicatePutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReplicatePutRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type ReplicateDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Envelope      *Envelope              `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateDeleteRequest) Reset() {
	*x = ReplicateDeleteRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateDeleteRequest) ProtoMessage() {}

func (x *ReplicateDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateDeleteRequest.ProtoReflect.Descriptor instead.
func (*ReplicateDeleteRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{16}
}

func (x *ReplicateDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReplicateDeleteRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type FetchVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchVersionRequest) Reset() {
	*x = FetchVersionRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchVersionRequest) ProtoMessage() {}

func (x *FetchVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchVersionRequest.ProtoReflect.Descriptor instead.
func (*FetchVersionRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{17}
}

func (x *FetchVersionRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type FetchVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Envelope      *Envelope              `protobuf:"bytes,3,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchVersionResponse) Reset() {
	*x = FetchVersionResponse{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchVersionResponse) ProtoMessage() {}

func (x *FetchVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchVersionResponse.ProtoReflect.Descriptor instead.
func (*FetchVersionResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{18}
}

func (x *FetchVersionResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *FetchVersionResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FetchVersionResponse) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type MemberState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Node             *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Status           MemberStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=nosql.cluster.v1.MemberStatus" json:"status,omitempty"`
	Incarnation      uint64                 `protobuf:"varint,3,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	LastSeenUnixNano int64                  `protobuf:"varint,4,opt,name=last_seen_unix_nano,json=lastSeenUnixNano,proto3" json:"last_seen_unix_nano,omitempty"`
	MembershipEpoch  uint64                 `protobuf:"varint,5,opt,name=membership_epoch,json=membershipEpoch,proto3" json:"membership_epoch,omitempty"`
	RangeMapEpoch    uint64                 `protobuf:"varint,6,opt,name=range_map_epoch,json=rangeMapEpoch,proto3" json:"range_map_epoch,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MemberState) Reset() {
	*x = MemberState{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberState) ProtoMessage() {}

func (x *MemberState) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberState.ProtoReflect.Descriptor instead.
func (*MemberState) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{19}
}

func (x *MemberState) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *MemberState) GetStatus() MemberStatus {
	if x != nil {
		return x.Status
	}
	return MemberStatus_MEMBER_STATUS_UNKNOWN
}

func (x *MemberState) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *MemberState) GetLastSeenUnixNano() int64 {
	if x != nil {
		return x.LastSeenUnixNano
	}
	return 0
}

func (x *MemberState) GetMembershipEpoch() uint64 {
	if x != nil {
		return x.MembershipEpoch
	}
	return 0
}

func (x *MemberState) GetRangeMapEpoch() uint64 {
	if x != nil {
		return x.RangeMapEpoch
	}
	return 0
}

type GossipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *MemberState           `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Membership    []*MemberState         `protobuf:"bytes,2,rep,name=membership,proto3" json:"membership,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{20}
}

func (x *GossipRequest) GetSender() *MemberState {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *GossipRequest) GetMembership() []*MemberState {
	if x != nil {
		return x.Membership
	}
	return nil
}

type GossipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Membership    []*MemberState         `protobuf:"bytes,2,rep,name=membership,proto3" json:"membership,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{21}
}

func (x *GossipResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GossipResponse) GetMembership() []*MemberState {
	if x != nil {
		return x.Membership
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *MemberState           `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	TargetNodeId  string                 `protobuf:"bytes,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{22}
}

func (x *PingRequest) GetSender() *MemberState {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *PingRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Responder     *MemberState           `protobuf:"bytes,2,opt,name=responder,proto3" json:"responder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{23}
}

func (x *PingResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PingResponse) GetResponder() *MemberState {
	if x != nil {
		return x.Responder
	}
	return nil
}

type IndirectPingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *MemberState           `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Target        *NodeInfo              `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndirectPingRequest) Reset() {
	*x = IndirectPingRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndirectPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndirectPingRequest) ProtoMessage() {}

func (x *IndirectPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndirectPingRequest.ProtoReflect.Descriptor instead.
func (*IndirectPingRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{24}
}

func (x *IndirectPingRequest) GetSender() *MemberState {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *IndirectPingRequest) GetTarget() *NodeInfo {
	if x != nil {
		return x.Target
	}
	return nil
}

type IndirectPingResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TargetAcknowledged bool                   `protobuf:"varint,2,opt,name=target_acknowledged,json=targetAcknowledged,proto3" json:"target_acknowledged,omitempty"`
	Responder          *MemberState           `protobuf:"bytes,3,opt,name=responder,proto3" json:"responder,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IndirectPingResponse) Reset() {
	*x = IndirectPingResponse{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndirectPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndirectPingResponse) ProtoMessage() {}

func (x *IndirectPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndirectPingResponse.ProtoReflect.Descriptor instead.
func (*IndirectPingResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{25}
}

func (x *IndirectPingResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *IndirectPingResponse) GetTargetAcknowledged() bool {
	if x != nil {
		return x.TargetAcknowledged
	}
	return false
}

func (x *IndirectPingResponse) GetResponder() *MemberState {
	if x != nil {
		return x.Responder
	}
	return nil
}

type MerkleRootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RangeStart    string                 `protobuf:"bytes,1,opt,name=range_start,json=rangeStart,proto3" json:"range_start,omitempty"`
	RangeEnd      string                 `protobuf:"bytes,2,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleRootRequest) Reset() {
	*x = MerkleRootRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleRootRequest) ProtoMessage() {}

func (x *MerkleRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleRootRequest.ProtoReflect.Descriptor instead.
func (*MerkleRootRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{26}
}

func (x *MerkleRootRequest) GetRangeStart() string {
	if x != nil {
		return x.RangeStart
	}
	return ""
}

func (x *MerkleRootRequest) GetRangeEnd() string {
	if x != nil {
		return x.RangeEnd
	}
	return ""
}

type MerkleRootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RootHash      []byte                 `protobuf:"bytes,2,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	ItemCount     uint64                 `protobuf:"varint,3,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleRootResponse) Reset() {
	*x = MerkleRootResponse{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleRootResponse) ProtoMessage() {}

func (x *MerkleRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleRootResponse.ProtoReflect.Descriptor instead.
func (*MerkleRootResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{27}
}

func (x *MerkleRootResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *MerkleRootResponse) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *MerkleRootResponse) GetItemCount() uint64 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

type StreamRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RangeStart    string                 `protobuf:"bytes,1,opt,name=range_start,json=rangeStart,proto3" json:"range_start,omitempty"`
	RangeEnd      string                 `protobuf:"bytes,2,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRangeRequest) Reset() {
	*x = StreamRangeRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRangeRequest) ProtoMessage() {}

func (x *StreamRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRangeRequest.ProtoReflect.Descriptor instead.
func (*StreamRangeRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{28}
}

func (x *StreamRangeRequest) GetRangeStart() string {
	if x != nil {
		return x.RangeStart
	}
	return ""
}

func (x *StreamRangeRequest) GetRangeEnd() string {
	if x != nil {
		return x.RangeEnd
	}
	return ""
}

type RepairKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*KeyEnvelope         `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepairKeysRequest) Reset() {
	*x = RepairKeysRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairKeysRequest) ProtoMessage() {}

func (x *RepairKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairKeysRequest.ProtoReflect.Descriptor instead.
func (*RepairKeysRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{29}
}

func (x *RepairKeysRequest) GetRows() []*KeyEnvelope {
	if x != nil {
		return x.Rows
	}
	return nil
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RangeStart    string                 `protobuf:"bytes,1,opt,name=range_start,json=rangeStart,proto3" json:"range_start,omitempty"`
	RangeEnd      string                 `protobuf:"bytes,2,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{30}
}

func (x *SnapshotRequest) GetRangeStart() string {
	if x != nil {
		return x.RangeStart
	}
	return ""
}

func (x *SnapshotRequest) GetRangeEnd() string {
	if x != nil {
		return x.RangeEnd
	}
	return ""
}

type SnapshotFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotFile) Reset() {
	*x = SnapshotFile{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotFile) ProtoMessage() {}

func (x *SnapshotFile) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotFile.ProtoReflect.Descriptor instead.
func (*SnapshotFile) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{31}
}

func (x *SnapshotFile) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SnapshotFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SnapshotFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Lsn           uint64                 `protobuf:"varint,2,opt,name=lsn,proto3" json:"lsn,omitempty"`
	Files         []*SnapshotFile        `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{32}
}

func (x *SnapshotResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SnapshotResponse) GetLsn() uint64 {
	if x != nil {
		return x.Lsn
	}
	return 0
}

func (x *SnapshotResponse) GetFiles() []*SnapshotFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type WALStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AfterLsn      uint64                 `protobuf:"varint,1,opt,name=after_lsn,json=afterLsn,proto3" json:"after_lsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALStreamRequest) Reset() {
	*x = WALStreamRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALStreamRequest) ProtoMessage() {}

func (x *WALStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALStreamRequest.ProtoReflect.Descriptor instead.
func (*WALStreamRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{33}
}

func (x *WALStreamRequest) GetAfterLsn() uint64 {
	if x != nil {
		return x.AfterLsn
	}
	return 0
}

type WALEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lsn           uint64                 `protobuf:"varint,1,opt,name=lsn,proto3" json:"lsn,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Envelope      *Envelope              `protobuf:"bytes,3,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Deleted       bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALEntry) Reset() {
	*x = WALEntry{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALEntry) ProtoMessage() {}

func (x *WALEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALEntry.ProtoReflect.Descriptor instead.
func (*WALEntry) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{34}
}

func (x *WALEntry) GetLsn() uint64 {
	if x != nil {
		return x.Lsn
	}
	return 0
}

func (x *WALEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WALEntry) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *WALEntry) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_cluster_v1_cluster_proto protoreflect.FileDescriptor

const file_cluster_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x18cluster/v1/cluster.proto\x12\x10nosql.cluster.v1\"E\n" +
	"\x10VectorClockEntry\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\acounter\x18\x02 \x01(\x04R\acounter\"K\n" +
	"\vVectorClock\x12<\n" +
	"\aentries\x18\x01 \x03(\v2\".nosql.cluster.v1.VectorClockEntryR\aentries\"\xc7\x01\n" +
	"\bEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12@\n" +
	"\fvector_clock\x18\x02 \x01(\v2\x1d.nosql.cluster.v1.VectorClockR\vvectorClock\x12/\n" +
	"\x14updated_at_unix_nano\x18\x03 \x01(\x03R\x11updatedAtUnixNano\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\"W\n" +
	"\vKeyEnvelope\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\benvelope\x18\x02 \x01(\v2\x1a.nosql.cluster.v1.EnvelopeR\benvelope\".\n" +
	"\x06Status\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"i\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12%\n" +
	"\x0eadvertise_addr\x18\x03 \x01(\tR\radvertiseAddr\"j\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\benvelope\x18\x02 \x01(\v2\x1a.nosql.cluster.v1.EnvelopeR\benvelope\x12\x12\n" +
	"\x04sync\x18\x03 \x01(\bR\x04sync\"m\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\benvelope\x18\x02 \x01(\v2\x1a.nosql.cluster.v1.EnvelopeR\benvelope\x12\x12\n" +
	"\x04sync\x18\x03 \x01(\bR\x04sync\"A\n" +
	"\rWriteResponse\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.nosql.cluster.v1.StatusR\x06status\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x8d\x01\n" +
	"\vGetResponse\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.nosql.cluster.v1.StatusR\x06status\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x126\n" +
	"\benvelope\x18\x03 \x01(\v2\x1a.nosql.cluster.v1.EnvelopeR\benvelope\"r\n" +
	"\x10RangeScanRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\x12\x19\n" +
	"\bpage_num\x18\x03 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"x\n" +
	"\x11RangeScanResponse\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.nosql.cluster.v1.StatusR\x06status\x121\n" +
	"\x04rows\x18\x02 \x03(\v2\x1d.nosql.cluster.v1.KeyEnvelopeR\x04rows\"\x0f\n" +
	"\rHealthRequest\"\x88\x01\n" +
	"\x0eHealthResponse\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.nosql.cluster.v1.StatusR\x06status\x12.\n" +
	"\x04node\x18\x02 \x01(\v2\x1a.nosql.cluster.v1.NodeInfoR\x04node\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\"_\n" +
	"\x13ReplicatePutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\benvelope\x18\x02 \x01(\v2\x1a.nosql.cluster.v1.EnvelopeR\benvelope\"b\n" +
	"\x16ReplicateDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\benvelope\x18\x02 \x01(\v2\x1a.nosql.cluster.v1.EnvelopeR\benvelope\"'\n" +
	"\x13FetchVersionRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x96\x01\n" +
	"\x14FetchVersionResponse\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.nosql.cluster.v1.StatusR\x06status\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x126\n" +
	"\benvelope\x18\x03 \x01(\v2\x1a.nosql.cluster.v1.EnvelopeR\benvelope\"\x99\x02\n" +
	"\vMemberState\x12.\n" +
	"\x04node\x18\x01 \x01(\v2\x1a.nosql.cluster.v1.NodeInfoR\x04node\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.nosql.cluster.v1.MemberStatusR\x06status\x12 \n" +
	"\vincarnation\x18\x03 \x01(\x04R\vincarnation\x12-\n" +
	"\x13last_seen_unix_nano\x18\x04 \x01(\x03R\x10lastSeenUnixNano\x12)\n" +
	"\x10membership_epoch\x18\x05 \x01(\x04R\x0fmembershipEpoch\x12&\n" +
	"\x0frange_map_epoch\x18\x06 \x01(\x04R\rrangeMapEpoch\"\x85\x01\n" +
	"\rGossipRequest\x125\n" +
	"\x06sender\x18\x01 \x01(\v2\x1d.nosql.cluster.v1.MemberStateR\x06sender\x12=\n" +
	"\n" +
	"membership\x18\x02 \x03(\v2\x1d.nosql.cluster.v1.MemberStateR\n" +
	"membership\"\x81\x01\n" +
	"\x0eGossipResponse\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.nosql.cluster.v1.StatusR\x06status\x12=\n" +
	"\n" +
	"membership\x18\x02 \x03(\v2\x1d.nosql.cluster.v1.MemberStateR\n" +
	"membership\"j\n" +
	"\vPingRequest\x125\n" +
	"\x06sender\x18\x01 \x01(\v2\x1d.nosql.cluster.v1.MemberStateR\x06sender\x12$\n" +
	"\x0etarget_node_id\x18\x02 \x01(\tR\ftargetNodeId\"}\n" +
	"\fPingResponse\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.nosql.cluster.v1.StatusR\x06status\x12;\n" +
	"\tresponder\x18\x02 \x01(\v2\x1d.nosql.cluster.v1.MemberStateR\tresponder\"\x80\x01\n" +
	"\x13IndirectPingRequest\x125\n" +
	"\x06sender\x18\x01 \x01(\v2\x1d.nosql.cluster.v1.MemberStateR\x06sender\x122\n" +
	"\x06target\x18\x02 \x01(\v2\x1a.nosql.cluster.v1.NodeInfoR\x06target\"\xb6\x01\n" +
	"\x14IndirectPingResponse\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.nosql.cluster.v1.StatusR\x06status\x12/\n" +
	"\x13target_acknowledged\x18\x02 \x01(\bR\x12targetAcknowledged\x12;\n" +
	"\tresponder\x18\x03 \x01(\v2\x1d.nosql.cluster.v1.MemberStateR\tresponder\"Q\n" +
	"\x11MerkleRootRequest\x12\x1f\n" +
	"\vrange_start\x18\x01 \x01(\tR\n" +
	"rangeStart\x12\x1b\n" +
	"\trange_end\x18\x02 \x01(\tR\brangeEnd\"\x82\x01\n" +
	"\x12MerkleRootResponse\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.nosql.cluster.v1.StatusR\x06status\x12\x1b\n" +
	"\troot_hash\x18\x02 \x01(\fR\brootHash\x12\x1d\n" +
	"\n" +
	"item_count\x18\x03 \x01(\x04R\titemCount\"R\n" +
	"\x12StreamRangeRequest\x12\x1f\n" +
	"\vrange_start\x18\x01 \x01(\tR\n" +
	"rangeStart\x12\x1b\n" +
	"\trange_end\x18\x02 \x01(\tR\brangeEnd\"F\n" +
	"\x11RepairKeysRequest\x121\n" +
	"\x04rows\x18\x01 \x03(\v2\x1d.nosql.cluster.v1.KeyEnvelopeR\x04rows\"O\n" +
	"\x0fSnapshotRequest\x12\x1f\n" +
	"\vrange_start\x18\x01 \x01(\tR\n" +
	"rangeStart\x12\x1b\n" +
	"\trange_end\x18\x02 \x01(\tR\brangeEnd\"L\n" +
	"\fSnapshotFile\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\x8c\x01\n" +
	"\x10SnapshotResponse\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.nosql.cluster.v1.StatusR\x06status\x12\x10\n" +
	"\x03lsn\x18\x02 \x01(\x04R\x03lsn\x124\n" +
	"\x05files\x18\x03 \x03(\v2\x1e.nosql.cluster.v1.SnapshotFileR\x05files\"/\n" +
	"\x10WALStreamRequest\x12\x1b\n" +
	"\tafter_lsn\x18\x01 \x01(\x04R\bafterLsn\"\x80\x01\n" +
	"\bWALEntry\x12\x10\n" +
	"\x03lsn\x18\x01 \x01(\x04R\x03lsn\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x126\n" +
	"\benvelope\x18\x03 \x01(\v2\x1a.nosql.cluster.v1.EnvelopeR\benvelope\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted*u\n" +
	"\fMemberStatus\x12\x19\n" +
	"\x15MEMBER_STATUS_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13MEMBER_STATUS_ALIVE\x10\x01\x12\x19\n" +
	"\x15MEMBER_STATUS_SUSPECT\x10\x02\x12\x16\n" +
	"\x12MEMBER_STATUS_DEAD\x10\x032\x86\x03\n" +
	"\vNodeService\x12D\n" +
	"\x03Put\x12\x1c.nosql.cluster.v1.PutRequest\x1a\x1f.nosql.cluster.v1.WriteResponse\x12J\n" +
	"\x06Delete\x12\x1f.nosql.cluster.v1.DeleteRequest\x1a\x1f.nosql.cluster.v1.WriteResponse\x12B\n" +
	"\x03Get\x12\x1c.nosql.cluster.v1.GetRequest\x1a\x1d.nosql.cluster.v1.GetResponse\x12T\n" +
	"\tRangeScan\x12\".nosql.cluster.v1.RangeScanRequest\x1a#.nosql.cluster.v1.RangeScanResponse\x12K\n" +
	"\x06Health\x12\x1f.nosql.cluster.v1.HealthRequest\x1a .nosql.cluster.v1.HealthResponse2\xa9\x02\n" +
	"\x12ReplicationService\x12V\n" +
	"\fReplicatePut\x12%.nosql.cluster.v1.ReplicatePutRequest\x1a\x1f.nosql.cluster.v1.WriteResponse\x12\\\n" +
	"\x0fReplicateDelete\x12(.nosql.cluster.v1.ReplicateDeleteRequest\x1a\x1f.nosql.cluster.v1.WriteResponse\x12]\n" +
	"\fFetchVersion\x12%.nosql.cluster.v1.FetchVersionRequest\x1a&.nosql.cluster.v1.FetchVersionResponse2\x82\x02\n" +
	"\rGossipService\x12K\n" +
	"\x06Gossip\x12\x1f.nosql.cluster.v1.GossipRequest\x1a .nosql.cluster.v1.GossipResponse\x12E\n" +
	"\x04Ping\x12\x1d.nosql.cluster.v1.PingRequest\x1a\x1e.nosql.cluster.v1.PingResponse\x12]\n" +
	"\fIndirectPing\x12%.nosql.cluster.v1.IndirectPingRequest\x1a&.nosql.cluster.v1.IndirectPingResponse2\x9a\x02\n" +
	"\x12AntiEntropyService\x12Z\n" +
	"\rGetMerkleRoot\x12#.nosql.cluster.v1.MerkleRootRequest\x1a$.nosql.cluster.v1.MerkleRootResponse\x12T\n" +
	"\vStreamRange\x12$.nosql.cluster.v1.StreamRangeRequest\x1a\x1d.nosql.cluster.v1.KeyEnvelope0\x01\x12R\n" +
	"\n" +
	"RepairKeys\x12#.nosql.cluster.v1.RepairKeysRequest\x1a\x1f.nosql.cluster.v1.WriteResponse2\xb7\x01\n" +
	"\x10BootstrapService\x12T\n" +
	"\vGetSnapshot\x12!.nosql.cluster.v1.SnapshotRequest\x1a\".nosql.cluster.v1.SnapshotResponse\x12M\n" +
	"\tStreamWAL\x12\".nosql.cluster.v1.WALStreamRequest\x1a\x1a.nosql.cluster.v1.WALEntry0\x01B)Z'nosqlEngine/src/cluster/transport/pb;pbb\x06proto3"

var (
	file_cluster_v1_cluster_proto_rawDescOnce sync.Once
	file_cluster_v1_cluster_proto_rawDescData []byte
)

func file_cluster_v1_cluster_proto_rawDescGZIP() []byte {
	file_cluster_v1_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_v1_cluster_proto_rawDesc), len(file_cluster_v1_cluster_proto_rawDesc)))
	})
	return file_cluster_v1_cluster_proto_rawDescData
}

var file_cluster_v1_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cluster_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_cluster_v1_cluster_proto_goTypes = []any{
	(MemberStatus)(0),              // 0: nosql.cluster.v1.MemberStatus
	(*VectorClockEntry)(nil),       // 1: nosql.cluster.v1.VectorClockEntry
	(*VectorClock)(nil),            // 2: nosql.cluster.v1.VectorClock
	(*Envelope)(nil),               // 3: nosql.cluster.v1.Envelope
	(*KeyEnvelope)(nil),            // 4: nosql.cluster.v1.KeyEnvelope
	(*Status)(nil),                 // 5: nosql.cluster.v1.Status
	(*NodeInfo)(nil),               // 6: nosql.cluster.v1.NodeInfo
	(*PutRequest)(nil),             // 7: nosql.cluster.v1.PutRequest
	(*DeleteRequest)(nil),          // 8: nosql.cluster.v1.DeleteRequest
	(*WriteResponse)(nil),          // 9: nosql.cluster.v1.WriteResponse
	(*GetRequest)(nil),             // 10: nosql.cluster.v1.GetRequest
	(*GetResponse)(nil),            // 11: nosql.cluster.v1.GetResponse
	(*RangeScanRequest)(nil),       // 12: nosql.cluster.v1.RangeScanRequest
	(*RangeScanResponse)(nil),      // 13: nosql.cluster.v1.RangeScanResponse
	(*HealthRequest)(nil),          // 14: nosql.cluster.v1.HealthRequest
	(*HealthResponse)(nil),         // 15: nosql.cluster.v1.HealthResponse
	(*ReplicatePutRequest)(nil),    // 16: nosql.cluster.v1.ReplicatePutRequest
	(*ReplicateDeleteRequest)(nil), // 17: nosql.cluster.v1.ReplicateDeleteRequest
	(*FetchVersionRequest)(nil),    // 18: nosql.cluster.v1.FetchVersionRequest
	(*FetchVersionResponse)(nil),   // 19: nosql.cluster.v1.FetchVersionResponse
	(*MemberState)(nil),            // 20: nosql.cluster.v1.MemberState
	(*GossipRequest)(nil),          // 21: nosql.cluster.v1.GossipRequest
	(*GossipResponse)(nil),         // 22: nosql.cluster.v1.GossipResponse
	(*PingRequest)(nil),            // 23: nosql.cluster.v1.PingRequest
	(*PingResponse)(nil),           // 24: nosql.cluster.v1.PingResponse
	(*IndirectPingRequest)(nil),    // 25: nosql.cluster.v1.IndirectPingRequest
	(*IndirectPingResponse)(nil),   // 26: nosql.cluster.v1.IndirectPingResponse
	(*MerkleRootRequest)(nil),      // 27: nosql.cluster.v1.MerkleRootRequest
	(*MerkleRootResponse)(nil),     // 28: nosql.cluster.v1.MerkleRootResponse
	(*StreamRangeRequest)(nil),     // 29: nosql.cluster.v1.StreamRangeRequest
	(*RepairKeysRequest)(nil),      // 30: nosql.cluster.v1.RepairKeysRequest
	(*SnapshotRequest)(nil),        // 31: nosql.cluster.v1.SnapshotRequest
	(*SnapshotFile)(nil),           // 32: nosql.cluster.v1.SnapshotFile
	(*SnapshotResponse)(nil),       // 33: nosql.cluster.v1.SnapshotResponse
	(*WALStreamRequest)(nil),       // 34: nosql.cluster.v1.WALStreamRequest
	(*WALEntry)(nil),               // 35: nosql.cluster.v1.WALEntry
}
var file_cluster_v1_cluster_proto_depIdxs = []int32{
	1,  // 0: nosql.cluster.v1.VectorClock.entries:type_name -> nosql.cluster.v1.VectorClockEntry
	2,  // 1: nosql.cluster.v1.Envelope.vector_clock:type_name -> nosql.cluster.v1.VectorClock
	3,  // 2: nosql.cluster.v1.KeyEnvelope.envelope:type_name -> nosql.cluster.v1.Envelope
	3,  // 3: nosql.cluster.v1.PutRequest.envelope:type_name -> nosql.cluster.v1.Envelope
	3,  // 4: nosql.cluster.v1.DeleteRequest.envelope:type_name -> nosql.cluster.v1.Envelope
	5,  // 5: nosql.cluster.v1.WriteResponse.status:type_name -> nosql.cluster.v1.Status
	5,  // 6: nosql.cluster.v1.GetResponse.status:type_name -> nosql.cluster.v1.Status
	3,  // 7: nosql.cluster.v1.GetResponse.envelope:type_name -> nosql.cluster.v1.Envelope
	5,  // 8: nosql.cluster.v1.RangeScanResponse.status:type_name -> nosql.cluster.v1.Status
	4,  // 9: nosql.cluster.v1.RangeScanResponse.rows:type_name -> nosql.cluster.v1.KeyEnvelope
	5,  // 10: nosql.cluster.v1.HealthResponse.status:type_name -> nosql.cluster.v1.Status
	6,  // 11: nosql.cluster.v1.HealthResponse.node:type_name -> nosql.cluster.v1.NodeInfo
	3,  // 12: nosql.cluster.v1.ReplicatePutRequest.envelope:type_name -> nosql.cluster.v1.Envelope
	3,  // 13: nosql.cluster.v1.ReplicateDeleteRequest.envelope:type_name -> nosql.cluster.v1.Envelope
	5,  // 14: nosql.cluster.v1.FetchVersionResponse.status:type_name -> nosql.cluster.v1.Status
	3,  // 15: nosql.cluster.v1.FetchVersionResponse.envelope:type_name -> nosql.cluster.v1.Envelope
	6,  // 16: nosql.cluster.v1.MemberState.node:type_name -> nosql.cluster.v1.NodeInfo
	0,  // 17: nosql.cluster.v1.MemberState.status:type_name -> nosql.cluster.v1.MemberStatus
	20, // 18: nosql.cluster.v1.GossipRequest.sender:type_name -> nosql.cluster.v1.MemberState
	20, // 19: nosql.cluster.v1.GossipRequest.membership:type_name -> nosql.cluster.v1.MemberState
	5,  // 20: nosql.cluster.v1.GossipResponse.status:type_name -> nosql.cluster.v1.Status
	20, // 21: nosql.cluster.v1.GossipResponse.membership:type_name -> nosql.cluster.v1.MemberState
	20, // 22: nosql.cluster.v1.PingRequest.sender:type_name -> nosql.cluster.v1.MemberState
	5,  // 23: nosql.cluster.v1.PingResponse.status:type_name -> nosql.cluster.v1.Status
	20, // 24: nosql.cluster.v1.PingResponse.responder:type_name -> nosql.cluster.v1.MemberState
	20, // 25: nosql.cluster.v1.IndirectPingRequest.sender:type_name -> nosql.cluster.v1.MemberState
	6,  // 26: nosql.cluster.v1.IndirectPingRequest.target:type_name -> nosql.cluster.v1.NodeInfo
	5,  // 27: nosql.cluster.v1.IndirectPingResponse.status:type_name -> nosql.cluster.v1.Status
	20, // 28: nosql.cluster.v1.IndirectPingResponse.responder:type_name -> nosql.cluster.v1.MemberState
	5,  // 29: nosql.cluster.v1.MerkleRootResponse.status:type_name -> nosql.cluster.v1.Status
	4,  // 30: nosql.cluster.v1.RepairKeysRequest.rows:type_name -> nosql.cluster.v1.KeyEnvelope
	5,  // 31: nosql.cluster.v1.SnapshotResponse.status:type_name -> nosql.cluster.v1.Status
	32, // 32: nosql.cluster.v1.SnapshotResponse.files:type_name -> nosql.cluster.v1.SnapshotFile
	3,  // 33: nosql.cluster.v1.WALEntry.envelope:type_name -> nosql.cluster.v1.Envelope
	7,  // 34: nosql.cluster.v1.NodeService.Put:input_type -> nosql.cluster.v1.PutRequest
	8,  // 35: nosql.cluster.v1.NodeService.Delete:input_type -> nosql.cluster.v1.DeleteRequest
	10, // 36: nosql.cluster.v1.NodeService.Get:input_type -> nosql.cluster.v1.GetRequest
	12, // 37: nosql.cluster.v1.NodeService.RangeScan:input_type -> nosql.cluster.v1.RangeScanRequest
	14, // 38: nosql.cluster.v1.NodeService.Health:input_type -> nosql.cluster.v1.HealthRequest
	16, // 39: nosql.cluster.v1.ReplicationService.ReplicatePut:input_type -> nosql.cluster.v1.ReplicatePutRequest
	17, // 40: nosql.cluster.v1.ReplicationService.ReplicateDelete:input_type -> nosql.cluster.v1.ReplicateDeleteRequest
	18, // 41: nosql.cluster.v1.ReplicationService.FetchVersion:input_type -> nosql.cluster.v1.FetchVersionRequest
	21, // 42: nosql.cluster.v1.GossipService.Gossip:input_type -> nosql.cluster.v1.GossipRequest
	23, // 43: nosql.cluster.v1.GossipService.Ping:input_type -> nosql.cluster.v1.PingRequest
	25, // 44: nosql.cluster.v1.GossipService.IndirectPing:input_type -> nosql.cluster.v1.IndirectPingRequest
	27, // 45: nosql.cluster.v1.AntiEntropyService.GetMerkleRoot:input_type -> nosql.cluster.v1.MerkleRootRequest
	29, // 46: nosql.cluster.v1.AntiEntropyService.StreamRange:input_type -> nosql.cluster.v1.StreamRangeRequest
	30, // 47: nosql.cluster.v1.AntiEntropyService.RepairKeys:input_type -> nosql.cluster.v1.RepairKeysRequest
	31, // 48: nosql.cluster.v1.BootstrapService.GetSnapshot:input_type -> nosql.cluster.v1.SnapshotRequest
	34, // 49: nosql.cluster.v1.BootstrapService.StreamWAL:input_type -> nosql.cluster.v1.WALStreamRequest
	9,  // 50: nosql.cluster.v1.NodeService.Put:output_type -> nosql.cluster.v1.WriteResponse
	9,  // 51: nosql.cluster.v1.NodeService.Delete:output_type -> nosql.cluster.v1.WriteResponse
	11, // 52: nosql.cluster.v1.NodeService.Get:output_type -> nosql.cluster.v1.GetResponse
	13, // 53: nosql.cluster.v1.NodeService.RangeScan:output_type -> nosql.cluster.v1.RangeScanResponse
	15, // 54: nosql.cluster.v1.NodeService.Health:output_type -> nosql.cluster.v1.HealthResponse
	9,  // 55: nosql.cluster.v1.ReplicationService.ReplicatePut:output_type -> nosql.cluster.v1.WriteResponse
	9,  // 56: nosql.cluster.v1.ReplicationService.ReplicateDelete:output_type -> nosql.cluster.v1.WriteResponse
	19, // 57: nosql.cluster.v1.ReplicationService.FetchVersion:output_type -> nosql.cluster.v1.FetchVersionResponse
	22, // 58: nosql.cluster.v1.GossipService.Gossip:output_type -> nosql.cluster.v1.GossipResponse
	24, // 59: nosql.cluster.v1.GossipService.Ping:output_type -> nosql.cluster.v1.PingResponse
	26, // 60: nosql.cluster.v1.GossipService.IndirectPing:output_type -> nosql.cluster.v1.IndirectPingResponse
	28, // 61: nosql.cluster.v1.AntiEntropyService.GetMerkleRoot:output_type -> nosql.cluster.v1.MerkleRootResponse
	4,  // 62: nosql.cluster.v1.AntiEntropyService.StreamRange:output_type -> nosql.cluster.v1.KeyEnvelope
	9,  // 63: nosql.cluster.v1.AntiEntropyService.RepairKeys:output_type -> nosql.cluster.v1.WriteResponse
	33, // 64: nosql.cluster.v1.BootstrapService.GetSnapshot:output_type -> nosql.cluster.v1.SnapshotResponse
	35, // 65: nosql.cluster.v1.BootstrapService.StreamWAL:output_type -> nosql.cluster.v1.WALEntry
	50, // [50:66] is the sub-list for method output_type
	34, // [34:50] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_cluster_v1_cluster_proto_init() }
func file_cluster_v1_cluster_proto_init() {
	if File_cluster_v1_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_v1_cluster_proto_rawDesc), len(file_cluster_v1_cluster_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_cluster_v1_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_v1_cluster_proto_depIdxs,
		EnumInfos:         file_cluster_v1_cluster_proto_enumTypes,
		MessageInfos:      file_cluster_v1_cluster_proto_msgTypes,
	}.Build()
	File_cluster_v1_cluster_proto = out.File
	file_cluster_v1_cluster_proto_goTypes = nil
	file_cluster_v1_cluster_proto_depIdxs = nil
}
